contact_links:
  - name: 📚 Documentation
    url: https://registry.npmjs.org
    about: Check documentation for usage
  - name: 💬 Discussions
    url: https://github.com/nuxt-community/design-tokens-module/discussions
    about: Use discussions if you have an idea for improvement and asking questions
